kind: Service
apiVersion: v1
metadata:
  name:  {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  selector:
    app: {{ .Release.Name }}-{{ .Chart.Name }}
  type:  ClusterIP 
  ports:
  - name:  tcp
    port:  80
    targetPort:  80