apiVersion: v1
kind: Pod
metadata:
  name: eyweb
  labels:
    name: eyweb
spec:
  containers:
  - name: eyweb
    image: eyweb:1.3
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    livenessProbe:
        httpGet:
          path: /ready.html
          port: 80
        initialDelaySeconds: 10
        timeoutSeconds: 2
        periodSeconds: 5
        failureThreshold: 1
